-- Mirai Orientation 2026: Supabase PostgreSQL Schema
-- Copy and run this script in your Supabase SQL Editor (Dashboard -> SQL Editor)

CREATE TABLE IF NOT EXISTS public.tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(50) NOT NULL,
    token_number INT NOT NULL,
    student_name VARCHAR(255) NOT NULL,
    mobile VARCHAR(20) NOT NULL,
    course VARCHAR(255) DEFAULT 'General',
    status VARCHAR(50) NOT NULL DEFAULT 'WAITING',
    table_number INT DEFAULT NULL,
    session_id VARCHAR(100) NOT NULL DEFAULT 'orientation-2026',
    called_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_session_token UNIQUE (session_id, token)
);

-- Enable RLS (Row Level Security) and grant public read/write access if desired
ALTER TABLE public.tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read and write access" ON public.tokens
    FOR ALL
    USING (true)
    WITH CHECK (true);
